# Python image to use
FROM Python:3.10

# Setting the working directory in the container
WORKDIR /app

# Copying the requirements file into the container at /app
COPY requirements.txt .

# Installing the requirements
RUN pip install --no-cache-dir -r requirements.txt

# Copying the rest of the working directory into the container at /app
COPY . .

# Running the app
CMD ["uvicon", "main:app", "--host", "0.0.0.0", "--port", "8000"]