version: '3.10'

services:
  app:
    build:
      context: .
      dockerfile: DockerFile
    container_name: ml_app
    command: bash -c "source venv/bin/activate && python app/main.py"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - mysql
    environment:
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
    networks:
      - ml_net

  redis:
    image: "redis:alpine"
    container_name: redis_cache
    ports:
      - "6379:6379"
    networks:
      - ml_net

  mysql:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - ml_net

volumes:
  mysql_data:

networks:
  ml_net:
